### ISSUE TITLE
关于《ChatGPT原理与实战》代码的数据问题

### ISSUE THREAD

**Issue by LinguaLogician** [liucongg/ChatGPTBook#1]
刘老师, 
      您好, 今日因为工作的需要, 拜读了您最近的著作《ChatGPT原理与实战》。在书中, 您系统地为梳理了ChatGPT相关的模型和算法技术, 并且对比了不同模型的特征和优劣, 这让我很全面地认识了ChatGPT 与其有关的预训练模型和大语言模型相关的知识。很钦佩您丰富的学识和深厚的实践, 同时, 我也为您的严谨和细致所感动。
      然而, 在通过对您提供的资料进行练习时, 发现您提供的数据好像有缺失, 因此希望能从您这里得到。
      **首先**, 对于您提供的第三章《3.5 基于夸夸闲聊数据的UniLM模型实战》部分的数据的链接, 无法访问。推测是因为数据中存在的敏感词汇所致。或许对此部分数据做压缩后上传, 便会解决链接失效的问题。
| data |[百度云](https://pan.baidu.com/s/1-fTaFTVwBSejSGCke-LM1g) |w8bd|
      **第二**, 我在对您的第五章中《5.4 基于提示的文本情感分析实战》(PromptProj)的代码进行调试时, 发现代码运行到data_set.py第50行时, 缺失data/train.json 文件, 导致运行时出现报错。
(报错)
      基于此, 想向您请求获取这两部分的数据, 不知可否麻烦您在百忙之中对邮件中的问题加以阅览, 并给出回复。
谢谢！

**Comment by liucongg** [comment]
第三章数据链接已经更新。
第五章，需要先运行data_helper.py代码生成data/train.json 文件

**Comment by LinguaLogician** [comment]
好的, 谢谢老师

**Comment by LinguaLogician** [comment]
好的, 谢谢老师！

________________________________
发件人: logCong ***@***.***>
发送时间: 2023年9月16日 0:48
收件人: liucongg/ChatGPTBook ***@***.***>
抄送: SwordManer ***@***.***>; Author ***@***.***>
主题: Re: [liucongg/ChatGPTBook] 关于《ChatGPT原理与实战》代码的数据问题 (Issue #1)


第三章数据链接已经更新。
第五章，需要先运行data_helper.py代码生成data/train.json 文件

―
