### ISSUE TITLE
本书第14页，倒数第2行 “解码层” 应为 “编码层”。

### ISSUE THREAD

**Issue by zhougz2018** [liucongg/ChatGPTBook#2]
由于BERT模型主要采用了**解码层**作为模型框架，所以该模型更擅长于语言表征言之，BERT 模型找到了一种有效的将文本转换成高维特征的方法。

**Comment by liucongg** [comment]
收到，已经记录到勘误内容中，在即将的新版本印刷中会修改该处的笔误内容
