### ISSUE TITLE
本书第18页，第7行，应为“解码类模型”

### ISSUE THREAD

**Issue by wangtao2001** [liucongg/ChatGPTBook#4]
原文：在ChatGPT各项任务表现优异的当下，编码类模型变成最为火热的模型，将有更多从业者投入到相关模型的设计优化中。
个人认为，本段描述的是GPT等此类解码类模型也可以做语义分析任务，从而吸引更多从业者进行研究，所以这里更改为“**解码类**模型变成最为火热的模型”更为合适。

**Comment by liucongg** [comment]
感谢反馈，这个我们已经记录到勘误内容中了，已经重新印刷，会进行修改，后面我们会放出来勘误表。由于笔误给您带来了不便。
